https://forums.autodesk.com/t5/inventor-forum/ilogic-naming-solid-bodies-with-dropdown-list-as-a-standard-name/m-p/7932826/highlight/true#M691065
https://inventortrenches.blogspot.com/search/label/Autodesk%20Inventor%20iLogic
https://download.autodesk.com/media/adn/DevTV_Introduction_to_Inventor_Programming/
https://inventortrenches.blogspot.com/search/label/Autodesk%20Inventor%20iLogic?updated-max=2014-06-10T16:29:00-05:00&max-results=20&start=6&by-date=false
http://www.hjalte.nl/75-multiselectlistbox
https://www.autodesk.com/support/technical/article/caas/tsarticles/ts/580m5V9igpBgk3WNek5Ydf.html



Function GetBOMRows(drawingDoc As DrawingDocument) As BOMRowsEnumerator
    Try
        Dim asm As AssemblyDocument = CType(refDoc, AssemblyDocument)
        Dim bom As BOM = asm.ComponentDefinition.BOM
        bom.StructuredViewEnabled = True
        bom.StructuredViewFirstLevelOnly = False

        For Each bomView As BOMView In bom.BOMViews
            If BOMView.ViewType = BOMViewTypeEnum.kStructuredBOMViewType Then
                Return BOMView.BOMRows
            End If
        Next
    Catch ex As Exception
        MessageBox.Show("Erro ao obter BOM Rows: " & ex.Message, "Erro", MessageBoxButtons.OK, MessageBoxIcon.Error)
    End Try

    Return Nothing
End Function

Sub AddBOMRowNode(row As BOMRow, parent As TreeNodeCollection, drawingDoc As DrawingDocument)
    Try
        ' Ignorar elementos do Content Center e estruturas nÃ£o normais
        If row.ComponentDefinitions IsNot Nothing AndAlso row.ComponentDefinitions.Count > 0 Then
            Dim defComp = row.ComponentDefinitions.Item(1)
            If TypeOf defComp Is PartComponentDefinition Then
                If CType(defComp, PartComponentDefinition).IsContentMember Then Return
            End If
            If defComp.BOMStructure <> BOMStructureEnum.kNormalBOMStructure Then Return
        End If
End try 
End sub 
